### PR TITLE
(Elon post) Submission of test blog post

### PR DESCRIPTION
**Pull request by securonomics**
Dinis,

Here is my submission for the test blog post. I will look forward to you contacting me.

Thanks,

-R

### CODE REVIEW

**Comment by DinisCruz** [comment]
Hi, can you resubmit this into the correct location? (Specially important is for the draft value to be set to true)

Thx

**Comment by securonomics** [comment]
Hey Dinis,

This is from the application process through Upwork. It was filed as part of my candidate test, so I'm not sure where the correct location is now. 

Let me know, and I will get it there.

-R

**Comment by DinisCruz** [comment]
don't worry I can do that (since I need to review it and merge it)

**Comment by m4sterbunny** [comment]
I have Rob's version and will use to improve existing edit.

**Comment by securonomics** [comment]
I’m still getting some of these e-mails when the project is something I worked on. Just an FYI.

-R

robert lemos | lemos associates llc
writer | data researcher | journalist
robert@lemosassociates.com | skype: rob.lemos | v: 603.755.6411

**Pull request closed without merging**
